# Generated by Django 4.2.7 on 2026-02-03 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('inward', 'Inward'), ('issued', 'Issued'), ('returned', 'Returned'), ('wastage', 'Wastage')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_type', models.CharField(max_length=50)),
                ('reference_id', models.PositiveIntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.rawmaterial')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='CurrentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.rawmaterial')),
            ],
            options={
                'unique_together': {('company', 'material')},
            },
        ),
    ]
