# Generated by Django 4.2.7 on 2026-02-03 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('skill_type', models.CharField(choices=[('stitching', 'Stitching'), ('button', 'Button'), ('collar', 'Collar'), ('color', 'Color')], max_length=20)),
                ('machine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('language_preference', models.CharField(choices=[('en', 'English'), ('gu', 'Gujarati')], default='en', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'mobile_number')},
            },
        ),
    ]
