# Generated by Django 4.2.7 on 2026-02-04 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('skill_type', models.CharField(choices=[('stitching', 'Stitching'), ('button', 'Button'), ('collar', 'Collar'), ('color', 'Color'), ('cuff', 'Shirt Cuff'), ('washing', 'Washing')], default='stitching', max_length=32)),
                ('machine_type', models.CharField(choices=[('simple', 'Simple silai machine'), ('munda', 'Munda machine'), ('other', 'Other')], default='simple', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('language_preference', models.CharField(choices=[('gu', 'Gujarati'), ('en', 'English')], default='gu', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='companies.company')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
            },
        ),
    ]
