# Generated by Django 4.2.7 on 2026-02-03 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
        ('materials', '0002_initial'),
        ('work_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdistribution',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker'),
        ),
        migrations.AddField(
            model_name='returnedmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.rawmaterial'),
        ),
        migrations.AddField(
            model_name='returnedmaterial',
            name='work_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='work_management.workreturn'),
        ),
        migrations.AddField(
            model_name='distributedmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.rawmaterial'),
        ),
        migrations.AddField(
            model_name='distributedmaterial',
            name='work_distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='work_management.workdistribution'),
        ),
        migrations.AlterUniqueTogether(
            name='worktype',
            unique_together={('company', 'name')},
        ),
    ]
