# Generated by Django 4.2.7 on 2026-02-04 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('companies', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_size', models.PositiveIntegerField()),
                ('distributed_date', models.DateField()),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_distributions', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='WorkReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_quantity', models.PositiveIntegerField()),
                ('pending_quantity', models.PositiveIntegerField()),
                ('wastage_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('return_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_returns', to='companies.company')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='work.workdistribution')),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_types', to='companies.company')),
            ],
            options={
                'verbose_name': 'Work Type',
                'verbose_name_plural': 'Work Types',
            },
        ),
        migrations.CreateModel(
            name='WorkReturnMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material')),
                ('work_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_materials', to='work.workreturn')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDistributionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_materials', to='work.workdistribution')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material')),
            ],
        ),
        migrations.AddField(
            model_name='workdistribution',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='work.worktype'),
        ),
        migrations.AddField(
            model_name='workdistribution',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='workers.worker'),
        ),
        migrations.CreateModel(
            name='MaterialInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_inwards', to='companies.company')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inwards', to='materials.material')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inwards', to='suppliers.supplier')),
            ],
        ),
    ]
