# Generated by Django 4.2.7 on 2026-02-06 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_quantity', models.PositiveIntegerField()),
                ('received_date', models.DateField()),
                ('quality_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('inspected', 'Inspected'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='received', max_length=16)),
                ('remarks', models.TextField(blank=True)),
                ('inspected_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_received', to='companies.company')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_works', to='work.workdistribution')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkReceivedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('returned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wastage_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material')),
                ('work_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_materials', to='work.workreceived')),
            ],
        ),
    ]
